### ISSUE TITLE
plt font not found

### ISSUE THREAD

**Issue by Aatroxion** [OneBST/GGanalysis#18]
报错：
findfont: Font family 'SHS-Bold' not found.
findfont: Font family 'SHS-Medium' not found.
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
是我的字体没有安装对位置还是需要修改配置？

**Comment by OneBST** [comment]
执行哪个文件的哪段代码出的问题？如果是字体位置问题的话可以尝试手动修改 [font_setting.py](https://github.com/OneBST/GGanalysis/blob/main/GGanalysis/font_setting.py) 内的内容，在 `fname` 中指定自己本地字体文件路径。
绘图字体方面确实设计的不好，以后会更换现有的绘图方式。如果不需要绘图的话可以不管这部分绘图代码，只做计算就好。

**Comment by Aatroxion** [comment]
执行
from GGanalysis.gacha_plot import DrawDistribution
fig = DrawDistribution(dist, dpi=72, show_description=True)
fig.draw_two_graph()
时报错
此时图片会无法显示中文


报错内容为：
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
findfont: Generic family 'sans-serif' not found because none of the following families were found: SHS-Regular
findfont: Font family 'SHS-Medium' not found.
findfont: Font family 'SHS-Medium' not found.
D:\anconda\envs\ai\lib\tkinter\__init__.py:839: UserWarning: Glyph 21452 (\N{CJK UNIFIED IDEOGRAPH-53CC}) missing from current font.
  func(*args)
findfont: Font family 'SHS-Bold' not found.
findfont: Font family 'SHS-Medium' not found.
findfont: Font family 'SHS-Bold' not found.

暂时没有找到好的解决方法
修改font_setting.py源文件
text_font = FontProperties('simhei', size=12)
title_font = FontProperties('simhei', size=18)
mark_font = FontProperties('simhei', size=12)
后可以解决

**Comment by OneBST** [comment]
安装了思源黑体吗？默认使用思源黑体字体，可以从[此处](https://github.com/adobe-fonts/source-han-sans)下载。Windows直接为全体用户安装就行。

**Comment by Aatroxion** [comment]
安装了但还是不行，替换font = FontProperties('simhei', size=12)倒是可以解决，（或许和python库版本和windows版本有关系？

**Comment by OneBST** [comment]
可能和这个模块找到的系统字体文件夹路径啥的有关系，画图方面的模块在重新封装了，之后会替换新的。先暂时凑合用这个吧。
