### ISSUE TITLE
請問武器池中的「命定值」是什麼？

### ISSUE THREAD

**Issue by seriaati** [OneBST/GGanalysis#2]

**Comment by OneBST** [comment]
是官方成为「神铸定轨」中的指标，详见[官方专栏](https://www.bilibili.com/read/cv12081866)
也就是玩家常说的定轨 0/2 1/2 2/2 强吃满定轨就是连续得了两个不是想要的五星武器后，下一个五星武器是定轨的那个
可能命定值和玩家常用的说法有所不同产生了一点理解困难，嗯
目前我工具包的解释还比较少，有什么问题可以问我

**Comment by seriaati** [comment]
所以命定值是一個介於 0~2 的數字？

**Comment by seriaati** [comment]
當命定值=2的時候，就是所謂大保底，所以 up_guarantee=1? 除了這個情況以外，up_guarantee 都等於 0 嗎？

**Comment by OneBST** [comment]
嗯，初始没有抽过卡池为0,
每次抽到非定轨五星时加1
当命定值为2时下次抽到五星必为定轨五星
抽到定轨五星时或者卡池轮换时命定值清零，命定值取值只有0/1/2

**Comment by OneBST** [comment]
> 當命定值=2的時候，就是所謂大保底，所以 up_guarantee=1? 除此之外，up_guarantee 都等於 0 嗎？

武器池是有大保底的，这个是和定轨系统独立的系统，在添加定轨系统之前就存在。`up_guarantee` 记录是否有武器池大保底
即每次抽到UP五星武器后（即UP的两个中任意一个），下次有25%概率抽到常驻武器，如果上次抽到的是常驻武器，下一个五星武器必为两个UP五星武器中的一个（也就是和角色池的大保底类似）
后来在这个基础上添加了定轨系统，所以情况变得更复杂一点。定轨系统优先级比以前的保底系统更高。

**Comment by seriaati** [comment]
所以只要最後一個抽到的武器是常駐，up_guarantee=1

**Comment by OneBST** [comment]
是的，只要最后一个是常驻，则 `up_guarantee=1`

记录 `up_guarantee`  为 `ug`，记录 `pity_point` 为` pp`。对于两个UP武器都不在常驻祈愿武器中的情况有以下转移关系。注意 ug1 pp0 的情况只存在于上个卡池最后一个五星武器为非UP五星武器，然后卡池轮换命定值清空的情况。

``` mermaid
graph LR
A[ug0 pp0] --25% 抽到常驻武器-->B[ug1 pp1]
A[ug0 pp0] --37.5% 抽到非定轨UP武器-->C[ug0 pp1]
A[ug0 pp0] --37.5% 抽到定轨UP武器-->A
B --50% 抽到定轨UP武器--> A
B --50% 抽到非定轨UP武器--> D[ug0 pp2]
C --25% 抽到常驻武器--> E[ug1 pp2]
C --37.5% 抽到非定轨UP武器-->D
C --37.5% 抽到定轨UP武器-->A
D --100%--> A
E --100%--> A
F[ug1 pp0] --50% 抽到非定轨UP武器--> C
F --50% 抽到定轨UP武器--> A
```

如果你需要把这个分析功能加入到 Discord bot 上，欢迎来问实现细节和怎么做更复杂的问题的分析，目前我文档写的还不是很好hhh。不过都是 python 应该好移植。如果想了解更多机制相关的信息可以去我的[b站](https://space.bilibili.com/6165300)上看专栏。

**Comment by seriaati** [comment]
好的，非常感謝你的熱心回答

**Comment by seriaati** [comment]
UP_5star_EP_weapon 計算的是獲得 UP 五星武器的機率，還是獲得定軌武器的機率？還是其他機率？

**Comment by OneBST** [comment]
是获得定轨武器的几率。准确的说是返回的获得定轨武器的抽数分布。
