### ISSUE TITLE
歐氣分析的範例好像寫錯了？

### ISSUE THREAD

**Issue by seriaati** [OneBST/GGanalysis#4]
做了以下簡單的測試：
```py
for index in range(1, 100):
        dist_c = GI.up_5star_character(item_num=index)
        player_luck = str(round(100 * sum((dist_c)[:1001]), 2)) #在同樣花了 1000 抽的人之中，抽到了 index 個 UP 五星，排名前 player_luck%
        print(f"{index} {player_luck}%")
```
結果當 index 越大時，player_luck 反而越小？這是不是反了？

**Comment by OneBST** [comment]
抱歉才看到这个 issue，我错过了邮箱通知。
`dist_c` 返回的是 `FiniteDist` 类型的分布信息，`dist_c[i]` 表示恰好在第 `i` 抽实现获得 `index` 个道具的概率。
`sum((dist_c)[:1001]` 表示在 1-1000 抽实现获得 `index` 个道具的概率和。
当道具数量越大的时候，想在 1-1000 抽内就达到目的的概率当然更低了。
应该是我起的变量名 `player_luck` 不够好导致了误解，这个值在这里其实是越小才表示运气越好的。按注释中的文字来理解就没问题：排名前 player_luck%。排名越靠前当然运气越好。
之后我想想怎么替换一下 `player_luck` 这个变量名，或许就叫达成概率 `achieving_p` 比较好。
