### ISSUE TITLE
关于函数返回结果的一些疑问

### ISSUE THREAD

**Issue by MilkWind** [OneBST/GGanalysis#5]
在调用函数前，没有对任何参数进行修改。
我分别进行了以下调用：
dist_c = AK.common_6star(item_num=1, pull_state=0)
print(dist_c.exp) # 实际结果34.59，理论抽数35
dist_c = AK.single_up_6star(item_num=1, pull_state=0)
print(dist_c.exp) # 实际结果69.18，理论抽数57
dist_c = AK.dual_up_specific_6star(item_num=1, pull_state=0)
print(dist_c.exp) # 实际结果138.37，理论抽数102
dist_c = AK.limited_up_6star(item_num=1, pull_state=0)
print(dist_c.exp) # 实际结果98.84，理论抽数70
除了获取到常规六星的理论抽数符合50%，其它的结果相对应的概率均偏高，是需要在调用前额外设置一些参数吗？

**Comment by OneBST** [comment]
调用 `dist.exp` 返回的是这段分布的期望，你想说的理论抽数我看了一下，似乎是50%概率位置。50%概率位置和期望位置不一定是一致的，当道具数量很多时，根据大数定理，这两个值会很接近，但是分布多种多样，不一定是重合的。
我建议你用以下代码画图来体会一下分布峰值和期望位置并没有很强的关联性：
``` python
import GGanalysis.games.arknights as AK
dist = AK.dual_up_specific_6star(item_num=1, pull_state=0)
# 导入绘图模块
from GGanalysis.gacha_plot import DrawDistribution
fig = DrawDistribution(dist, dpi=72, max_pull=400, show_description=False)
fig.draw_two_graph()
```
