### ISSUE TITLE
包含多次抽卡和原始补充的成功率计算

### ISSUE THREAD

**Issue by luanjunyi** [OneBST/GGanalysis#54]
# 背景

在现实中，玩家经常需要评估一个抽卡规划的可行性。例如两个版本可以获得220抽，这时候抽一个0+1，再过半个版本获得70抽，需要抽一个上半的0+0，跳过下半版本，在下一个版本的末期，又获得了300抽，这时候想抽一个1+1。那么这些武器和角色都抽出来的概率有多大？

我写了一个实现：https://gist.github.com/luanjunyi/77b1f36236360fe3d714ad3198c9a260

思路是枚举第一次出金所需要所有的可能抽数，之后的所有金数变成了一个规模-1的子问题，可以递归解决。用记忆化搜索可以避免重复计算。但是状态好像是190^n，n是需要抽的总金数，180是大保底数。

更多背景在我的专栏里：https://www.bilibili.com/read/cv39435901/

# 可能的集成方案

模拟具体抽卡计划可行性可以作为GGanalysis的一个扩展，这应该是和DualPityModel等模型同一个抽象层次的类，每个game各自设置。

# 可能的优化
多数玩家需要规划的金数都不多，如果金数多，抽卡成本会收敛到数学期望，所以这个计算的作用会随着金数需求提升而下降。因此虽然有上面时间复杂度的问题，依然是可用的。不过可能依然有改进的空间。

**Comment by OneBST** [comment]
有时间复杂度低很多同时利用当前框架实现简便的方法。本质上计算能在各个阶段的抽数限制下都能达成目标的玩家占比，可以**视为剔除每轮分布中超出抽数限制部分玩家对应概率空间的过程**。以你的计算为例：抽0+1同时限制200抽，直接丢掉分布中花费超过200抽的部分玩家就行了；然后接下来在追加74抽的预算继续抽0+0，只要把之前的剩余分布卷积获得一个角色的分布，然后丢掉花费超过274抽部分的分布即可。这样进行剔除操作就不需要为每个剩余抽数开状态来记录了，复杂度等级是 $O(N\log N)$，其中 $N$ 是最后得到分布的总长度，避免了指数上升的状态空间，我实测下来也快非常多。

``` python
from GGanalysis import FiniteDist
import GGanalysis.games.zenless_zone_zero as ZZZ
# 要抽的道具数量以及阶段预算
tasks = [
    [1, 1, 200],
    [1, 0, 74],
    [1, 1, 40],
]
total_pulls = 0
ans_dist = FiniteDist([1])
for (num_c, num_w, task_pulls) in tasks:
    total_pulls += task_pulls
    ans_dist *= ZZZ.up_5star_character(num_c) * ZZZ.up_5star_weapon(num_w)
    ans_dist.dist = ans_dist.dist[:total_pulls+1]
print("成功概率", sum(ans_dist.dist))
ans_dist.p_normalization()  # 归一化
print("成功玩家平均花费", ans_dist.exp)
```

不过我看你的代码加了不少缓存环节，我在想如果我给 `ZZZ.up_5star_character(num_c)` 这种调用加上缓存会不会可以更快一点，也不会多占用什么内存。不过因为返回的玩意不是原生的 python 结构，有点麻烦。

**Comment by OneBST** [comment]
所以大概不需要为每个游戏专门定义模型。可能把这样的操作写进在线文档的例子里面比较方便参考？

**Comment by OneBST** [comment]
我又思考了一下，我这个算法的复杂度是 $O(k^2\log{k})$ 这里的 $k$ 是中间要抽到的道具数量（认为获取不同道具的所需的抽数分布差不多长），然后有一个比较大的常数。因为这里最坏的情况是逐次卷积，用不上框架里用快速幂思想优化的卷积，所以达不到一般情况下的 $O(N \log{N})$。相关信息我更新到了[在线文档](https://onebst.github.io/GGanalysis/start_using/check_gacha_plan.html)里，这样估计更有帮助。

**Comment by luanjunyi** [comment]
说几个我的发现。

1. 你的卷积算法和我的记忆化搜索结果是一致的。我构造了6个case，应该是没问题的。
* 这是我更新了一些接口后的记忆化算法实现：https://gist.github.com/luanjunyi/77b1f36236360fe3d714ad3198c9a260
* 这是优化了接口后的卷积实现：https://gist.github.com/luanjunyi/60317d907520148c365fef908f7c912b
* 这是测试代码：https://gist.github.com/luanjunyi/1ad991fc1047d2464b494ae99ae9379f

2. 上面的测试代码包含性能测试。如果只运行一遍，也就是只运行最后Timer的部分，不运行之前的其他case，那么搜索的时间比conv的时间大概慢100倍。有趣的是，如果先运行其他小case，再运行最后的Timer，搜索的时间几乎可以忽略不计，而conv需要2.3ms。我猜想是python的@cache在一次执行后并不会删除，因此cache对性能的提升很大。这个发现很让我意外!

3. 有可能卷积算法没有@cache up_5star_character之类的计算导致的

**Comment by OneBST** [comment]
缓存的影响没有那么大，提升最大的场景在上次记录了答案后这次直接返回，即反复查询同一个问题的情况，这种情况在实践中很少。而使用搜索会产生指数级别的状态空间，还是使用卷积方法比较好。
后面更改了 `FiniteDist` 的设置，现在不能直接用 `ans_dist.dist = ans_dist.dist[:total_pulls+1]` 来设置分布了，使用方法可以参考[在线文档](https://onebst.github.io/GGanalysis/start_using/check_gacha_plan.html)。
