### ISSUE TITLE
关于崩铁抽卡规则的问题

### ISSUE THREAD

**Issue by Silencersn** [OneBST/GGanalysis#64]
> 当未触发UP或保底规则时，所有角色或光锥均分基础出率

### 问题1
抽取限定角色池时，如果抽取到的是4星对象，且未触发UP或保底规则，那么这个4星对象有无可能是UP4星角色？
或者说，如果未触发UP或保底规则，那么这个4星对象是在`所有4星角色及所有4星光锥`中抽取，还是在`非UP4星角色及所有4星光锥`中抽取？

### 问题2
抽取限定角色池时，如果抽取到的是4星对象，且未触发UP或保底规则，那么接下来如何选择这个4星对象是角色还是光锥？

### 问题3
抽取限定角色池时，在未触发UP或保底规则的情况下抽取到UP5星角色或UP4星角色（假设在问题1中有可能），是否会被判定为歪了，从而在下一次触发保底。

### 模拟
我写了一段模拟选择4星对象的代码，伪码如下：

```
// 在已经抽取到4星对象的情况下，选择具体是那种4星对象
Star4Item GetStar4Item(bool 有保底)
{
    if (有保底 || 50%的概率)
    {
        return UP4星角色中的一个;
    }

    if (50%的概率) // 对应问题2：这里的条件应该是什么？
    {
        return 所有4星角色中的一个; // 对应问题1：这里应为所有4星角色中的一个，还是非UP4星角色中的一个？
    }
    else
    {
        return 所有4星光锥中的一个;
    }
}
```

对于上述代码，暴力模拟出来的结果中：
对于UP4星角色的占比，与期望及统计站的结果相似（问题1的影响不大）
对于非UP4星角色和4星光锥的占比，与统计站的数据差异较大（如在最新的黄泉复刻池中，单个非UP4星角色占比约为0.22%，而模拟结果约为0.78%，不排除是我其它部分的代码写得有问题的可能）

### 其它
该问题可能与本项目关联不大，但因为我想不到还可以在哪问（挠头），所以在这里发个issue，不好意思，提前感谢

**Comment by OneBST** [comment]
**问题1**
未触发UP时选取的4星对象中应该没有UP4星角色，因为UP占比比较符合2/3。
**问题2**
有平稳机制介入，可以参考[这个视频](https://www.bilibili.com/video/BV1nt421w7FE/)2:42附近的描述，参数我嫌麻烦没去拆崩铁的，你可以[参考这里](https://zhuanlan.zhihu.com/p/701617041)套原神的试试。因为这个机制导致你的模拟和统计值对不上。
**问题3**
假设UP概率为0.5+a，如果a这部分之后下个五星100%是UP，可以算得抽一个UP的期望为 $\frac{1.5}{1+a}$ 个五星。和直接设置为 $2-\frac{1.5}{1+a}$ 的UP概率区别体现在出现连金的可能更高。而我们测出来概率是56.25%左右，如果50%/8这种抽到了列表里的UP的情况下次还不歪，那么直接测的概率会是58.82%会更高。同时直接看小保底序列是可以过随机序列测试的，本次小保底没有和上一个小保底有相关性，所以问题3的假说应该不成立。代码应该是通过本次获得的道具是否为UP来重置大保底的。
