### ISSUE TITLE
如何自定义5/6星干员up数量模型

### ISSUE THREAD

**Issue by MilkWind** [OneBST/GGanalysis#8]
在GGanalysis/games/arknights/gacha_model.py文件中，默认提供了多种5/6星干员up数量模型（例如获取单UP5星 single_up_specific_5star、获取双UP6星中的特定6星 dual_up_specific_6star），用户只需传入需求数量和已有水位，即可获得相对应卡池的期望/方差/分布数据。
但如果用户想要自定义5/6星干员up数量模型，例如<联合行动>，4个up六星（暂无模型）、6个up五星（暂无模型）；或是<定向寻访>，3个up六星（暂无模型），3个up五星（已提供模型-获取三UP5星中的特定5星 triple_up_specific_5star ，但模型感觉对不上，应该是BernoulliGachaModel(P_5STAR_AVG * 0.6 / 3)？），应该如何做？

**Comment by OneBST** [comment]
UP五星我是按照UP概率50%，有几类就几类进行平分设置的，所以代码里定义的3UP五星是对应的 `BernoulliGachaModel(P_5STAR_AVG/2/3)`。如果实际上不是这样，而是UP率60%，那我就要改一下了。不过实际上五星也有概率上升，但我懒得写模型了，所以就用了伯努利分布近似。
如果不考虑更复杂的机制，可以使用 `PityBernoulliModel(dist_of_item, p)` 来定义获取一个星级的道具后，想要的那个道具占比为 `p` 的模型。你可以用这个来进行定义。

**Comment by MilkWind** [comment]
比如说这样？

`# 定向寻访池
    # 六星100%概率，UP三个，故抽到目标UP六星的概率为1/3
    # 五星60%概率，UP三个，故抽到目标UP五星的概率为0.6/3
    elif card_pool_type == 5:
        if star_level == 6:
            triple_up_specific_6star = PityBernoulliModel(PITY_6STAR, 1 / 3)
            dist = triple_up_specific_6star(success_count, pull_state=existing_water_level)
        elif star_level == 5:
            triple_up_specific_5star_new = PityBernoulliModel(PITY_5STAR, 0.6 / 3)
            dist = triple_up_specific_5star_new(success_count, pull_state=existing_water_level)
    return [dist.exp, dist.var]  # [期望,方差]`

**Comment by MilkWind** [comment]
是这样吗？
success_count 是期望抽出的次数
existing_water_level 是已垫的水位

    # 定向寻访池
    # 六星100%概率，UP三个，故抽到目标UP六星的概率为1/3
    # 五星60%概率，UP三个，故抽到目标UP五星的概率为0.6/3
    elif card_pool_type == 5:
        if star_level == 6:
            triple_up_specific_6star = PityBernoulliModel(PITY_6STAR, 1 / 3)
            dist = triple_up_specific_6star(success_count, pull_state=existing_water_level)
        elif star_level == 5:
            triple_up_specific_5star_new = PityBernoulliModel(PITY_5STAR, 0.6 / 3)
            dist = triple_up_specific_5star_new(success_count, pull_state=existing_water_level)
    return [dist.exp, dist.var]  # [期望,方差]

**Comment by OneBST** [comment]
`triple_up_specific_6star = PityBernoulliModel(PITY_6STAR, 1 / 3)` 后面可能需要填 1/6？毕竟UP也有一定概率，不是100%都是UP
如果3UP五星池子UP率是60%的话，我还得改改。
其他的没什么问题

**Comment by MilkWind** [comment]
> `triple_up_specific_6star = PityBernoulliModel(PITY_6STAR, 1 / 3)` 后面可能需要填 1/6？毕竟UP也有一定概率，不是100%都是UP 如果3UP五星池子UP率是60%的话，我还得改改。 其他的没什么问题

定向寻访池确实是100%up三个六星，应该是1/3没错。

**Comment by OneBST** [comment]
那我改改五星，改成三UP时60%是UP

**Comment by MilkWind** [comment]
如果想要获得“抽到某个卡池所有UP干员”的数据，该怎么定义模型？
`dual_up_specific_6star`是获取双UP6星中的特定6星模型，但如果定义为`dual_up_specific_6star(2, 0)`，应该是计算“抽到双UP池中的特定六星两次”的数据，这和“抽到双UP池中的所有UP干员”数据应该不一样，毕竟抽到所有UP干员的要求没有获取先后次序的要求，先获取哪个UP干员都可以。

**Comment by OneBST** [comment]
直接使用 `both_up_6star` 可以计算双UP时集齐两种UP6星所需抽数的概率分布 
如果有更多种类的6星，可以使用 `AK_Limit_Model` 进行定义
如果想要进一步自定义，你可能需要使用集齐道具层 `Coupon_Collector_layer` 等并参考其他地方如 ``AK_Limit_Model`` 的代码。

**Comment by MilkWind** [comment]
> 直接使用 `both_up_6star` 可以计算双UP时集齐两种UP6星所需抽数的概率分布 如果有更多种类的6星，可以使用 `AK_Limit_Model` 进行定义 如果想要进一步自定义，你可能需要使用集齐道具层 `Coupon_Collector_layer` 等并参考其他地方如 `AK_Limit_Model` 的代码。

了解了，我去研究研究(￣▽￣)

**Comment by MilkWind** [comment]
```
class BernoulliLayer(GachaLayer):
    # 伯努利抽卡层
    def __init__(self, p, e_error = 1e-8, max_dist_len=1e5) -> None:
        super().__init__()
        self.p = p  # 伯努利试验概率
        self.e_error = e_error  # 期望的误差限制
        self.max_dist_len = max_dist_len
        self.exp = 1/p
        self.var = (p**2-2*p+1)/((1-p)*p**2) #这一句好像限定了六星的up概率比例不能达到100%☆
```

即
```
    # 定向寻访池
    # 六星100%概率，UP三个，故抽到目标UP六星的概率为1/3
    elif card_pool_type == 5:
        triple_up_specific_6star = AK.AK_Limit_Model(AK.PITY_6STAR, 1, collect_item=3) #概率不能设置为1☆
        distribution = triple_up_specific_6star(1, pull_state=existing_water_level)
```

在线文档中好像也没有相应的解决方案，这个...

**Comment by OneBST** [comment]
修改了一下 `BernoulliLayer` 的代码，现在支持概率设置为 1 的情况了。
这部分设计之初就没有考虑要允许概率为 1，因为概率为 1 的时候对应不添加这一层。不过为了更好的适应性还是增加了支持，感谢你提出这个问题。
另外对于这个问题，更应该发 **feature request** ，单独开一个 issue 来说明问题，并表示希望给 `BernoulliLayer` 添加 `p=1` 时候的支持。

**Comment by MilkWind** [comment]
好像并没有完全解决...
`Traceback (most recent call last):  File "C:\Users\Administrator\Desktop\GGanalysis-main\GGanalysisCaller\caller.py", line 147, in <module>    distribution = general_calculation_all_operators(*data_list[1:])  File "C:\Users\Administrator\Desktop\GGanalysis-main\GGanalysisCaller\caller.py", line 130, in general_calculation_all_operators    triple_up_specific_6star = AK.AK_Limit_Model(AK.PITY_6STAR, 1, collect_item=3)  File "C:\Users\Administrator\Desktop\GGanalysis-main\GGanalysis\games\arknights\gacha_model.py", line 52, in __init__    self.layers.append(CouponCollectorLayer(2, collect_item))  File "C:\Users\Administrator\Desktop\GGanalysis-main\GGanalysis\gacha_layers.py", line 206, in __init__    self.exp, self.var = self._calc_exp_var(0, self.target_types)  File "C:\Users\Administrator\Desktop\GGanalysis-main\GGanalysis\gacha_layers.py", line 215, in _calc_exp_var    ans_exp += self.types / (self.types-i+1)ZeroDivisionError: division by zero`

**Comment by OneBST** [comment]
你的这个问题从 `BernoulliLayer` 变成了 `CouponCollectorLayer`，阅读 `AK_Limit_Model` 发现该处代码定义 `CouponCollectorLayer` 中定义的总种数固定为2，传入的 `collect_item` 为需要集齐的种数，我修改一下让总种数也可以自定义好了

**Comment by OneBST** [comment]
现在填写需要的总数量就可以解决这个问题了，之前报错是因为总数为2种，要求抽到3种
``` python
AK.AK_Limit_Model(AK.PITY_6STAR, 1, total_item_types=3,  collect_item=3)
```

**Comment by MilkWind** [comment]
解决了！ｄ(･∀･*)♪ﾟ
